### PR TITLE
adds a new .ini entry to enable/disable the logger

### PR DESCRIPTION
**Pull request by shinobu**
This pull requests adds the log.enable into the config and changes the referring lines in the code from log.level checks to log.enable checks and adds the entry into the about page

### CODE REVIEW

**Review by white-gecko — CHANGES_REQUESTED** [review]
- [x] manual review commits
- [ ] manual check that log enable/disable works
  - it works for ontowiki.log
  - erfurt.log and query.log is still active, if `log.enabled = false`
- [x] check unit tests:
  - OK (86 tests, 154 assertions)
- [ ] check integration tests mysql (skipped)
- [x] check integration tests virtuoso:
  - FAILURES! Tests: 27, Assertions: 138, Errors: 1.

Please also implement the same behavior for `log.enabled = false` as it is form `log.level = 0`. This means, also the erfurt logs should be disabled.

**Comment by shinobu** [comment]
done in  https://github.com/AKSW/Erfurt/pull/135 @white-gecko

**Comment by white-gecko** [comment]
executed tests rebased to develop (9c20df62b889955981bddaa846978fe55ca6de89)

- [x] manual review commits
- [x] manual check that log enable/disable works
- [x] check unit tests:
    * OK (86 tests, 154 assertions)
- [x] check integration tests virtuoso:
    * OK (45 tests, 229 assertions)
- [x] check integration tests mysql:
    * OK (45 tests, 229 assertions)
- [x] check extension tests:
    * OK (11 tests, 59 assertions)

**Review by white-gecko — CHANGES_REQUESTED** [review]
Still disabling log doesn't disable erfurt and query log.

**Comment by shinobu** [comment]
white-gecko did you chose the correct Erfurt version? The pr https://github.com/AKSW/Erfurt/pull/135 in Erfurt isnt merged yet either

*edit

I tested it locally and it does work for me 
The About page shows, that the logger is deactivated
Setting the log.level to 7 and creating a knowledgebase/triple -> no logs
Turning the Logger back on and doing the same -> logs

**Review by white-gecko — APPROVED** [review]

**Pull request merged**
