### PR TITLE
Run composer update and update composer.lock

### PR DESCRIPTION
**Pull request by white-gecko**
composer update running in PHP 5.4 for most compatibility

### CODE REVIEW

**Comment by white-gecko** [comment]
@shinobu did you also check if this looks good in the UI?

**Comment by pfrischmuth** [comment]
Installing dependencies works

**Review by pfrischmuth — APPROVED** [review]
LGTM

**Comment by white-gecko** [comment]
There is also a php codesniffer update coming with it, but should not cause trouble

**Pull request merged**
