### PR TITLE
Integrate support for Stardog backend

### PR DESCRIPTION
**Pull request by pfrischmuth**
- add default config values for stardog backend to config default
  files
- adjust integration test bootstrap to allow stardog backend

### CODE REVIEW

**Review by shinobu — CHANGES_REQUESTED** [review]
Could you please add stardogs as an option in the makefile and in the .travis.yml?

furthermore (not exactly relevant for this pull request) i tested the usual function with stardogs, everything seems to be a bit slower and furthermore the rdfauthor functions `add property` and `add instance` dont work properly (endless loading times etc).

**Comment by shinobu** [comment]
@k00ni you have some experience with stardog in docker regarding the license. Could you help us, on how to initialise our tests against a stardog backend?

**Comment by k00ni** [comment]
Uff, i am not very familiar with Stardog. If i remember it right, Stardog uses a simple SPARQL endpoint for interactions (in comparison to Virtuoso with ODBC). Maybe you start there? Can you explain what you meant with "initialize" tests? Whats your current approach?

**Comment by shinobu** [comment]
the issue lies more into how to integrate stardog into travis
stardog requires a license, even docker container for stardogs require licenses
(example: https://hub.docker.com/r/bluepeppers/stardog/ )
@k00ni 

how did you/would you solve that issue -> I'd guess we would need to somehow make a (AKSW?) (community?) license, but I dont know if we can somehow give only travis (and not public) access rights to that, so thats one of the things I'm unsure how to solve right now.

**Comment by k00ni** [comment]
Ah, i got what you want. Stardog company doesn't want you to use their software without a license. Therefore, no way in here, i am afraid. 

But you should ask them, if they provide a basic license for you/OntoWiki. Outline, that supporting OntoWiki is a good thing, because its a major RDF software, well known in the community and wants to use a "real" triple store. If you hesitate with that, just drop me a mail or paste your work here and i support you here.

**Comment by shinobu** [comment]
I'd say, that it should be @white-gecko 's decision to get us a key (you can talk with him about this).

We can probably encrypt the file for the travis tests like this:
https://docs.travis-ci.com/user/encrypting-files/

**Comment by k00ni** [comment]
> I'd say, that it should be @white-gecko 's decision to get us a key (you can talk with him about this).

Why? You are assigned to this issue as well as reviewer, therefore entitled to decide. @white-gecko reads the comments here and will talk to you, off- or online about this, if he think its important. But its usually a good way to save peoples time by acting (and ask for forgiveness later), instead of asking everytime :) (no offence)

The link about encryption seems like an overkill and is not helping with this issue, in my opinion, because we would still need Stardogs permission and license.

**Comment by shinobu** [comment]
the link about encryption was for the case that we do get a license (file), if we would upload that plain, people could just abuse it

and about white-gecko, he is the Headdeveloper for OntoWiki and with a request to stardog/creating a common public license for it, I would represent OntoWiki (and partially the AKSW) and I think i'm in no position to just do that.

**Pull request closed without merging**
