### PR TITLE
Add extension management with composer/installers

### PR DESCRIPTION
**Pull request by white-gecko**
With this commit OntoWiki extensions can be installed using
https://github.com/composer/installers

~~This pull request needs changes in `composer.json` when https://github.com/composer/installers/pull/356 is accepted.~~

### CODE REVIEW

**Comment by white-gecko** [comment]
The pull-request for composer/installers is accepted in version 1.3.0 :-)

**Comment by white-gecko** [comment]
This should not be merged before https://github.com/AKSW/OntoWiki/pull/428

**Comment by pfrischmuth** [comment]
Hi @white-gecko Please rebase

**Comment by white-gecko** [comment]
There is also a php codesniffer update coming with it, but should not cause trouble

**Review by pfrischmuth — APPROVED** [review]
Changes as discussed... LGTM

**Pull request merged**
