### PR TITLE
fix #407 by using authorLabel instead of author

### LINKED ISSUE #407: OntoWiki uses doap.n3's author property instead of authorLabel
In all doap.n3 files you only set `authorLabel`, but not `author`. The extension exconf tries to use `author` property in its list.phtml, but fails in doing so. Why? I am not sure yet. But it can't handle CubeViz's [doap.n3](https://github.com/AKSW/cubeviz.ontowiki/blob/master/doap.n3.dist) file for instance.

The problem is, that if you using CubeViz, you will run into an exception in the extension configuration view, for instance.

I created a small fix and will make a pull request.

### PR DESCRIPTION
**Pull request by k00ni**
Background information can be found in issue #407.

### CODE REVIEW

**Review by shinobu — APPROVED** [review]
no tests fail, you can merge this @white-gecko

**Comment by white-gecko** [comment]
@shinobu did you also check if this looks good in the UI?

**Comment by shinobu** [comment]
no I didnt, i'm going to check it soon

**Review by shinobu — CHANGES_REQUESTED** [review]
every single author entry disappears (they are all correctly shown prior)
-> this needs to be fixed if the issue actually still exists @k00ni

**Comment by shinobu** [comment]
I wrote the issues with this pull request into the issue #407 .
This pullrequest should be either accordingly fixed or closed.

**Comment by k00ni** [comment]
I am not sure about this issue anymore. What would be your preferred solution @shinobu?

**Comment by shinobu** [comment]
I guess the best solution will be to just fix the doap.n3 and turn the 2 authorlabel's entries into one @k00ni .

**Comment by k00ni** [comment]
Ok, so be it :)

**Pull request closed without merging**
